-- AlterTable
ALTER TABLE "User"
ADD COLUMN "targetScore" INTEGER,
ADD COLUMN "examDate" DATE,
ADD COLUMN "dailyStudyMinutes" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN "language" TEXT NOT NULL DEFAULT 'vi',
ADD COLUMN "audioAutoplay" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "audioVolume" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN "audioPlaybackRate" DOUBLE PRECISION NOT NULL DEFAULT 1,
ADD COLUMN "reduceMotion" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "highContrast" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN "largeText" BOOLEAN NOT NULL DEFAULT false;
